services:

  # OPTIONAL // depends if you have already postgres and want just another DB
  db:
    image: postgres:17

    profiles: # remove if you want to import it to like portainer and run everything
      - database

    container_name: postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: HexoraITApp
      POSTGRES_USER: HexoraIT
      POSTGRES_PASSWORD: HexoraIT

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
      
  # Just ui to check the postgresql its fully optional if you have already client or another app to check out dbs
  adminer:
    image: adminer

    profiles: # remove if you want to import it to like portainer and run everything
      - database

    container_name: adminer

    restart: unless-stopped

    ports:
      - "8082:8080"

    depends_on:
      - db

  api:
    image: lewan24/hexorait-api:latest
    container_name: hexoraitapi

    restart: unless-stopped

    ports:
      - "8081:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Production

      ConnectionStrings__Default: >
        Host=db;
        Port=5432;
        Database=HexoraITApp;
        Username=HexoraIT;
        Password=HexoraIT
        
      Jwt__Issuer: HexoraITApp
      Jwt__Audience: HexoraITApp.Client
      # Use custom 32-byte secret key22
      Jwt__SigningKey: YOUR_SUPER_SECRET_KEY11111111111

      # you can create a volume and bind to it to store documents somewhere like on another server or something
      FileStorage__RootPath: /app/storage

      AppSettings__ITDocsAdmin: admin@HexoraIT.pl
      AppSettings__AllowRegister: false
      # Make sure there is provided your domain (frontend) url, this is required for CORS settings and security
      AppSettings__AllowOrigins__0: "http://localhost:80"
      AppSettings__AllowOrigins__1: "http://localhost"

  frontend:
    image: lewan24/hexorait-web:latest
    container_name: hexoraitweb

    restart: unless-stopped

    ports:
      - "80:80"

    environment:
      # API url, the target domain where the ITDocs will be available at
      HEXORAIT_API_BASE_URL: http://localhost:8081/api

    depends_on:
      - api

volumes:
  postgres-data:
